### PR TITLE
Add Docker support

### PR DESCRIPTION
**Pull request by monfresh**
**Why**: To make it easier for people to install the project on their
machines.

### CODE REVIEW

**Comment by monfresh** [comment]
@md5 The Rails version specified in the Docker image does not affect the app. The app will only use what's installed by `bundle install`.

**Comment by md5** [comment]
The version in the image only affects things in terms of bloating the image
with unused gem versions if there is a difference, but the Debian-based
images are already pretty huge compared to the Alpine-based ones like
ruby:2.3.1-alpine.

**Comment by monfresh** [comment]
Ah. I see. So you would recommend using the alpine images, and then copy over the necessary setup for Node and Postgres from the Rails image?

**Comment by md5** [comment]
I think for this application the Alpine base image would be great.

**Comment by monfresh** [comment]
Looks like the Alpine image doesn't work out of the box. I'll merge this in for now, and we can explore Alpine later.

**Comment by md5** [comment]
FYI, I ended up spending some time getting the app up and running under `ruby:2.3.1-alpine`: https://github.com/codeforamerica/ohana-web-search/compare/master...appropriate:alpine

It's still not possible to run tests, though, since getting `phantomjs` to work under Alpine is still a work in progress.

**Pull request merged**
