### PR TITLE
Added platform configuration helper

### PR DESCRIPTION
**Pull request by CristianCurteanu**

### CODE REVIEW

**Comment by monfresh** [comment]
Thanks for your contribution. Could you please explain what problem this PR is solving?

**Comment by CristianCurteanu** [comment]
I decided it could be handy to configure some parts of app from YAML files, as in this case to extract hardcoded URLs into a config file. But it can be useful for other things (ex. flags)

**Comment by monfresh** [comment]
I agree that it makes sense to allow some parts of the app to be configured via YAML, such as `application.yml`, `settings.yml`, and i18n. However, I don't think the JSON for the root endpoint is worth making customizable in this way. 

I find this code is a lot harder to read. I don't think it's worth adding 30 lines of code with very little difference in customizability. Is the difference between editing the `root_controller.rb` file versus the YAML file big enough to justify the additional complexity? I would say no, but I'm open to hearing convincing arguments if you have any.

I also don't expect most people will want to customize this. If they do, they will also need to update the `routes.rb` file, which means they are technically savvy, and if they are, they should be able to edit the `root_controller.rb` file directly.

I'm curious to know whether you had a need to customize the endpoints, and if so, in what way?

**Comment by monfresh** [comment]
Closing this due to inactivity.

**Pull request closed without merging**
