### PR TITLE
Implement deploy to Heroku with one-click button 

### PR DESCRIPTION
**Pull request by volkanunsal**
I used the new [app.json](https://devcenter.heroku.com/articles/app-json-schema) protocol to implement this button so users can create a Heroku app instantly. I had to change a few things in the default setup. Notably, moved the admin and confirmation emails into application.yml so they can be configured on the Heroku web interface. 

This is what the button looks like:

screen shot 2014-08-26 at 1 09 27 pm

### CODE REVIEW

**Comment by volkanunsal** [comment]
Finally finished with this Here is what it looks like now:

screen shot 2015-01-12 at 1 10 27 pm

**Comment by volkanunsal** [comment]
There are a few breaking tests because I modified the `entity_importer` a little bit. The missing but required check is looking at the name of the file in the file system, but if the file is a Tempfile, as it is when you are working with an uploaded file, then the name of the file is not something that is in our control. My solution was to loosen the check so it doesn't care about the required files list. I know this is probably too lax, so I'd be happy what would work better here.

**Comment by volkanunsal** [comment]
> Coverage decreased (-49.64%) 

I think I know how that happened.

**Comment by monfresh** [comment]
In an issue, you said:
> I cannot figure this out at all. The routes for /api and /admin are completely missing after the app is deployed to Heroku with app.json. The ENV values that these routes depend on are all there. I tried to reproduce this locally and failed. I tried deploying the same app from CLI and couldn't reproduce it then either, even though the ENV values are exact the same. So I don't know what makes these routes disappear all of a sudden.

I looked at `app.json` in your PR and noticed that there are some missing ENV vars from `application.yml`, like `ENABLE_HTTPS`, which is required in production, and I noticed that you added additional env vars and marked them as required, but you did not add a value for them. I would start there and make sure the env vars match `application.yml` exactly.

I greatly appreciate all the effort you've been putting into this, but I wanted to point out that not every repo is a candidate for a one-click Heroku deployment. Ohana API seems like it's not a great fit for that magical button, which is perfectly fine. I'd hate for you to keep spending so much time if it's not meant to be.

For this to work, the tests should definitely continue to pass as is, and we should definitely not remove the file checks. Since Heroku only allows writing to files temporarily, you'd have to store the files on S3 to use their expected names, but that would introduce another dependency and more complexity.

The current deployment process is not that complicated, but it can definitely be improved by combining all the various commands that need to be run into one. Pretty much every major step is already automated. We just need to consolidate them into one script. We have scripts for automatically generating CSV files from your Google account, for pushing the code to Heroku, setting up Heroku, and for importing the CSV files into the DB. The only "technical" thing a non-technical person would need to do is type in one command in Terminal.

**Comment by volkanunsal** [comment]
I may have been wrong about the read-only file system. Apparently, it's [an ephemeral file system.](https://devcenter.heroku.com/articles/dynos#ephemeral-filesystem) But even if I fixed that, it seems like there are other issues with certain things not being in ENV variables and whatnot, and that's a much deeper question and I'm not going to push you on that point much further. 

My last argument for app,json would be that, looking at it psychologically, deploying something from the web versus from the Terminal is kind of like the difference between "free" and "has a cost." Everything you can do for yourself is free. Everything you need to ask others for has a cost. I've been doing the costly bit of helping non-technical people get setup with Ohana recently, and I don't see them firing up the terminal and typing in commands as easily as opening their browsers and clicking buttons, and uploading files. I think it'd help the adoption of Ohana if one-click deployment were an option. 

At the very least, though, the web based file uploader can be extracted from this PR because it is pretty neat in its ability to show the dependencies between the files visually. When you upload an organization, for example, it unlocks the other files that require orgs to be in the system first, so it's a much more user-friendly approach that administrators might be able to catch-on pretty quickly. I can pull that out into a separate PR if there is any interest.

**Comment by monfresh** [comment]
Good point about the psychological aspect, but I'd like to give people more credit. I think very clear written instructions with plenty of screenshots, along with a video tutorial, can go a long way. Before spending more time trying to make everything web-based, I think we should do some usability tests with non-technical people and see how they feel about the "follow these instructions" approach. If they can follow along just fine, then we're done. Otherwise, we'll find out which part they're getting stuck on, and see how we can improve that part.

I'll work on consolidating the scripts and beefing up the documentation. Then I'll test them locally with non-technical people and observe.

Having said all of that, the maintenance of this project absolutely requires technical knowledge. Initial deployment is just one aspect. Someone will have to update gems, pull in any updates from this upstream repo, troubleshoot Heroku issues, add Heroku add-ons for logs and monitoring, and maybe perform some data cleanup that should be scripted. Using this project cannot be completely "free".

**Pull request closed without merging**
